name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - run: go test -coverprofile=coverage.txt -covermode=atomic ./...
      - uses: codecov/codecov-action@v4